FROM openjdk:16-jdk-slim
EXPOSE 8080

ENV TZ=Asia/Seoul

ARG JDBC_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG JWT_SECRET_KEY

ENV JDBC_URL ${JDBC_URL}
ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}
ENV JWT_SECRET_KEY ${JWT_SECRET_KEY}

COPY ./application-infrastructure/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
