spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: mysql
  datasource:
    url: ${JDBC_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  jackson:
    property-naming-strategy: SNAKE_CASE
  lifecycle:
    timeout-per-shutdown-phase: 20s
server:
  servlet:
    context-path: /v1/applications
  shutdown: graceful
  
auth:
  jwt:
    secret: ${JWT_SECRET_KEY}