spring:
  application:
    name: v1-application-service
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:https://api.xquare.app/cloud-config/
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME:xquare-config-username}
      password: ${CLOUD_CONFIG_PASSWORD:xquare-config-password}
